export const ACCOUNT_STATUSES = [
    "PENDING_VERIFICATION",
    "ACTIVE",
    "SUSPENDED",
    "DISABLED",
];
export const NOTIFICATION_CATEGORIES = [
    "LEARNING",
    "ASSIGNMENT",
    "DDP",
    "TEST",
    "MENTOR",
    "ANNOUNCEMENT",
    "CERTIFICATE",
    "ACCOUNT",
];
export const NOTIFICATION_PRIORITIES = ["LOW", "NORMAL", "HIGH"];
export const PROGRAM_SORTS = ["featured", "newest", "duration", "name"];
export const BATCH_STATUSES = ["DRAFT", "UPCOMING", "OPEN", "FULL", "IN_PROGRESS", "COMPLETED", "CANCELLED"];
export const ENROLLMENT_STATUSES = ["PENDING", "ACTIVE", "COMPLETED", "WITHDRAWN", "SUSPENDED"];
export const CURRICULUM_STATUSES = ["DRAFT", "PUBLISHED", "ARCHIVED"];
export const DAY_AVAILABILITY = ["LOCKED", "AVAILABLE", "IN_PROGRESS", "COMPLETED"];
export const CONTENT_TYPES = ["VIDEO", "LESSON", "NOTE", "RESOURCE", "PRACTICE", "DDP", "ASSIGNMENT", "TEST"];
export const ACTIVITY_STATUS = ["NOT_STARTED", "IN_PROGRESS", "COMPLETED"];
export const QUESTION_TYPES = ["MCQ_SINGLE", "MCQ_MULTIPLE", "TRUE_FALSE"];
export const DDP_STATUS = ["DRAFT", "PUBLISHED", "ARCHIVED"];
export const ATTEMPT_STATUS = ["IN_PROGRESS", "SUBMITTED", "AUTO_SUBMITTED", "EXPIRED"];
export const ASSIGNMENT_TYPES = ["TEXT", "FILE_UPLOAD", "LINK"];
export const ASSIGNMENT_STATUSES = ["DRAFT", "PUBLISHED", "ARCHIVED"];
export const SUBMISSION_STATUSES = [
    "DRAFT",
    "SUBMITTED",
    "UNDER_REVIEW",
    "EVALUATED",
    "RETURNED",
    "RESUBMISSION_REQUIRED",
];
export const ASSIGNMENT_RESOURCE_TYPES = ["LINK", "PDF", "GITHUB", "DOC", "OTHER"];
